### PR TITLE
Update build-osx.md

### PR DESCRIPTION
**Pull request by mohker-83010**
see "OSX executable? #39" in issues tab for notes and work in progress information.

### CODE REVIEW

**Comment by mohker-83010** [comment]
EYE think EYE am waiting on some kind of review merge thingy now? :D

**Comment by squidicuzz** [comment]
The file you changed is a markdown file.  What does this accomplish?
I am not sure what these changes do or why they need to be included at this time...

**Comment by 2a5A1Ghu1** [comment]
Work around for this issue was answered in https://github.com/stakecube/StakeCubeCoin/issues/39

If you would like to build the wallet from scratch the current directions are correct but it is recommended to also build depends as our build system uses the library versions we test and build against. The brew libraries can are in most cases aggressively updated and can break compilation. Currently we are shipping an unsigned binary but this should be remedied in later releases.

For instructions on how to build depends you can begin by reading them here.
https://github.com/stakecube/StakeCubeCoin/tree/develop/depends

**Review by 2a5A1Ghu1 — CHANGES_REQUESTED** [review]
The changes submitted resolve nothing and in fact introduce confusion. Personally I am actually confused what the reason for the commit was made in the first place as the aforementioned issue is not associated with the build docs. Also markdown uses html style comments. Please explain the issue and how this commit resolves the issue.

**Comment by mohker-83010** [comment]
yes, the intent is, to not mislead those into using "Homebrew" tools, that would compromise OSX stuff thingys.

EYE use // comment out, to leave this for reference and provide notification, as a bit of a warning label for new users who may not comprehend what is going.

the "Homebrew" tools are unnecessary.

my other intention is to update the OSX install info, with the proper use of Apple Xcode software, once a troll easy button smash is worked out. :D

**Comment by mohker-83010** [comment]
contrib/macdeploy/README.md has extensive discussion on the official build tools for Darwin/osx/Xcode.
possibly a more updated version at bitcoincore, same file structure is there but have not compared the two.
working through this now.
a more simplified version for build-osx.md is needed.

**Comment by squidicuzz** [comment]
Closing as this pull request does not meet proper standards for contribution or code requirements.

**Pull request closed without merging**
